# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/120yJijLbrs1M6P6vSBwKEE7QjjezwYGf
"""

productos = [
    {"nombre": "Curso de Python", "precio": 120, "stock": 40, "tipo": "curso"},
    {"nombre": "Plantilla Excel Finanzas", "precio": 25, "stock": 75,"tipo": "plantilla"},
    {"nombre": "Ebook Inteligencia Artificial", "precio": 60, "stock": 22, "tipo": "ebook"},
    {"nombre": "Software de Gestión de Tareas", "precio": 210, "stock": 12, "tipo": "software"},
    {"nombre": "Curso de Visualización de Datos", "precio": 180, "stock": 18, "tipo": "curso"},
    {"nombre": "Plantilla CV Creativo", "precio": 15, "stock": 100, "tipo": "plantilla"},
    {"nombre": "Ebook de Productividad", "precio": 35, "stock": 60, "tipo": "ebook"},
    {"nombre": "Licencia App de Notas", "precio": 85, "stock": 8, "tipo": "software"},
]
def clasificar_precio(precio):
    if precio < 50:
        return "Muy económico"
    elif 50 <= precio <= 200:
        return "Rango medio"
    else:
        return "Premium"

def obtener_descuento(stock):
    if stock > 50:
        return 25
    elif 20 <= stock <= 50:
        return 15
    elif 10 <= stock <= 20:
        return 5
    else:
        return 0
def aplicar_descuento(precio, porcentaje):
    descuento = precio * (porcentaje / 100)
    precio_final = precio - descuento
    return round(precio_final, 2)

valor_total_sin_descuento = 0
valor_total_con_descuento = 0

for producto in productos:
    nombre = producto["nombre"]
    precio = producto["precio"]
    stock = producto["stock"]

    clasificacion = clasificar_precio(precio)
    porcentaje = obtener_descuento(stock)
    precio_final = aplicar_descuento(precio, porcentaje)

    subtotal_sin_descuento = precio * stock
    subtotal_con_descuento = precio_final * stock

    valor_total_sin_descuento += subtotal_sin_descuento
    valor_total_con_descuento += subtotal_con_descuento

    print(f"🧾 Producto: {nombre}")
    print(f"   Clasificación: {clasificacion}")
    print(f"   Precio unitario original: ${precio}")
    print(f"   Descuento aplicado: {porcentaje}%")
    print(f"   Precio final con descuento: ${precio_final}")
    print(f"   Stock disponible: {stock}")
    print(f"   Subtotal con descuento: ${subtotal_con_descuento:.2f}\n")

print("💰 Valor total sin descuento:", round(valor_total_sin_descuento, 2))
print("💰 Valor total con descuento:", round(valor_total_con_descuento, 2))
print("💸 Ahorro total:", round(valor_total_sin_descuento - valor_total_con_descuento, 2))